# DO NOT CHANGE
init:
  ps: |
    $ErrorActionPreference = "Stop"
    Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
    Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here
environment:
  global:
    WARNINGS_ARE_ERRORS: 1.0
    R_REMOTES_STANDALONE: yes
    USE_RTOOLS: yes
    R_CHECK_INSTALL_ARGS: --install-args=--build
    R_CHECK_ARGS: --as-cran --no-multiarch

  matrix:
  - R_VERSION: stable
    RTOOLS_VERSION: 35
    R_ARCH: x64
    CRAN: http://cran.rstudio.com

  - R_VERSION: stable
    RTOOLS_VERSION: 35
    R_ARCH: i386
    CRAN: http://cran.rstudio.com

build_script:
  - travis-tool.sh install_deps
  - R -e "if (!ROpenCVLite::isOpenCVInstalled()) ROpenCVLite::installOpenCV(batch = TRUE)"
  - R -e "if (unlist(strsplit(as.character(utils::packageVersion('ROpenCVLite')), '[.]'))[3] != gsub('[^0-9]', '', ROpenCVLite::opencvVersion())) ROpenCVLite::installOpenCV(batch = TRUE)"

test_script:
  - R -e "ROpenCVLite::opencvConfig('libs', arch = Sys.getenv('R_ARCH'))"
  - R -e "ROpenCVLite::opencvConfig('cflags', arch = Sys.getenv('R_ARCH'))"
  - R -e "ROpenCVLite::opencvVersion()"
  - travis-tool.sh run_tests

on_failure:
  - choco install dependencywalker -y --allow-empty-checksums
  - depends.exe /f:1 /c /oc:C:/projects/rvision/Rvision.Rcheck/depends.txt C:/projects/rvision/Rvision.Rcheck/00_pkg_src/Rvision/src/Rvision.dll
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs
  - path: '*.Rcheck\**\*.out'
    name: Logs
  - path: '*.Rcheck\**\*.fail'
    name: Logs
  - path: '*.Rcheck\**\*.Rout'
    name: Logs
  - path: '\*_*.tar.gz'
    name: Bits
  - path: '\*_*.zip'
    name: Bits

deploy:
  provider: GitHub
  description: Windows Binary
  auth_token:
    secure: h+8/Q2kGkLoaoZ8OEtsplJGXuPFhS/VQbtE66cMJj7J3PeDgNAROVkV7368h3s+b
  draft: no
  prerelease: no
  on:
    APPVEYOR_REPO_TAG: true
